= adduce

*_adduce_* is a node.js package which reads the contents of file and http(s) URLs from the command line, interprets them as JSON files, merges their contents and passes it to an application as a single JavaScript object.
It is intended to be used in preference to the practice of using the NODE_ENV environment variable to set configuration settings.
*_adduce_* is the spiritual successor to the <<#user-content-ref-1,sn-props>> package which is no longer maintained.
*_adduce_* also adds the ability to listen for a configuration update before starting the app.

:toc:

== Introduction and Motivation

For years the typical pracice for configuring node.js applications is to hard-code configuration settings into the application, using the NODE_ENV environment variable to select from different application profiles.
Setting NODE_ENV to "prod" would select the production configuration settings while setting it to "dev" would select the development settings.
Additional environments such as "test" or "perf" could be added for QA or performance testing.

While this is a very simple technique for handling multiple application profiles, it is not without its faults.
More than once we have seen database passwords hard-coded in applications.
This is bad.
It also _requires_ a code change when configuration settings change.
For more details, see the text "<<#user-content-ref-2,Is NODE_ENV an Anti-Pattern?>>" (referenced below.)

Simply put, *_adduce_* allows an application developer to start a program like this:

....
#!/usr/bin/env node
// simple_server - a simple test server

require( 'adduce' )
  .startup( props => {
     console.log( 'properties:\n' + JSON.stringify( props ) );

     // Rest of the program goes here.
} );
....

And when the program is started like this:

....
$ simple_server --config file://app_server.json --config https://int.example.com/app_2122.json
....

Then the contents of the app_server.json file and the app_2122.json file are merged into a single JavaScript object and passed to the callback function passed as a parameter to the startup() function.
This is useful because it allows a developer to split machine specific configuration and application specific configuration into two files: the local and the remote.
The local config file would likely be delivered along with the application, perhaps in a container, while the remote config file would be hosted on an internal configuration site.
The developer could use any number of config files, depending on their need.

== Managing Keys and Secrets

If you are comfortable hosting keys and secrets on a server that any internal client can read, you can simply include them in the remote configuration.
Alternately, you can use *_adduce_* to listen for updates from a key management service.
The code would change to include a reference to the update() function, like so:

....
#!/usr/bin/env node
// simple_server - a simple test server

require( 'adduce' )
  .startup( props => {
    console.log( 'startup properties:\n' + JSON.stringify( props ) );

    // Don't start the application yet.
  } )
  .update( props => {
    console.log( 'update properties:\n' + JSON.stringify( props ) );

    // Presumably the update properties contain credentials for back-end systems.
    // Now that we have them, we can start the application
  } );
....

And you would start the program like this:

....
$ simple_server \
    --config file://app_server.json \
    --config https://int.example.com/app_2122.json \
    --update 'IPv4:@en0:9043' \
    --update-root file://update_root.pem
....

The '--update' command line option specifies the ip address and port to listen for updates while the '--update-root' command line option specifies the location of a trusted root certificate.
Systems attempting to connect to the update port will need to use a client-side certificate which derives from this root.

== References

1. [[ref-1]] https://www.npmjs.com/package/sn-props
2. [[ref-2]] https://meadhbh.hamrick.rocks/home/technical-sh-t/is-node_env-an-anti-pattern
